"""add player raffle media

Revision ID: 12efb8bd6d7b
Revises: a74cc7663f97
Create Date: 2025-11-25 15:43:02.536230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12efb8bd6d7b'
down_revision: Union[str, Sequence[str], None] = 'a74cc7663f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffles', sa.Column('player_photo_id', sa.String(length=100), nullable=True))
    op.add_column('raffles', sa.Column('player_video_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'player_video_id')
    op.drop_column('raffles', 'player_photo_id')
    # ### end Alembic commands ###
