"""edit channel

Revision ID: 17ccb278f558
Revises: ab664c81702a
Create Date: 2025-11-21 18:03:06.367635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ccb278f558'
down_revision: Union[str, Sequence[str], None] = 'ab664c81702a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('can_post', sa.Boolean(), nullable=False))
    op.add_column('channels', sa.Column('can_edit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'can_edit')
    op.drop_column('channels', 'can_post')
    # ### end Alembic commands ###
