"""add unique for raffle channels

Revision ID: 1fa024b628ce
Revises: 17ccb278f558
Create Date: 2025-11-22 12:19:07.609604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa024b628ce'
down_revision: Union[str, Sequence[str], None] = '17ccb278f558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'raffle_channels', ['channel_id', 'raffle_id', 'channel_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raffle_channels', type_='unique')
    # ### end Alembic commands ###
