"""delete file_path

Revision ID: 251d8b0c4f16
Revises: e865c3a867e1
Create Date: 2025-11-19 15:09:26.918820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251d8b0c4f16'
down_revision: Union[str, Sequence[str], None] = 'e865c3a867e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffles', sa.Column('file_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
