"""add ref parent

Revision ID: 3983fcf75327
Revises: 12efb8bd6d7b
Create Date: 2025-11-25 17:17:23.132674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3983fcf75327'
down_revision: Union[str, Sequence[str], None] = '12efb8bd6d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle_players', sa.Column('ref_parent', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffle_players', 'ref_parent')
    # ### end Alembic commands ###
