"""edit channel

Revision ID: a4f80f2a191c
Revises: 87930e2523d3
Create Date: 2025-11-21 17:40:13.701313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f80f2a191c'
down_revision: Union[str, Sequence[str], None] = '87930e2523d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'channels', ['username'])
    op.create_unique_constraint(None, 'channels', ['chat_id'])
    op.drop_column('channels', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'creator_id')
    # ### end Alembic commands ###
