"""edit table raffle_players

Revision ID: a74cc7663f97
Revises: f61a070b57bd
Create Date: 2025-11-25 12:14:41.258685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74cc7663f97'
down_revision: Union[str, Sequence[str], None] = 'f61a070b57bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('p_uq_id'), 'raffle_players', type_='unique')
    op.create_unique_constraint('p_uq_id', 'raffle_players', ['user_id', 'raffle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('p_uq_id', 'raffle_players', type_='unique')
    op.create_unique_constraint(op.f('p_uq_id'), 'raffle_players', ['id', 'raffle_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
