"""edit channel

Revision ID: ab664c81702a
Revises: 103d53d7af4b
Create Date: 2025-11-21 17:55:47.203568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab664c81702a'
down_revision: Union[str, Sequence[str], None] = '103d53d7af4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
