"""add place to player

Revision ID: af5e9838238c
Revises: 3983fcf75327
Create Date: 2025-11-27 14:22:03.355503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5e9838238c'
down_revision: Union[str, Sequence[str], None] = '3983fcf75327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle_players', sa.Column('place', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffle_players', 'place')
    # ### end Alembic commands ###
