"""edit channel

Revision ID: cd0cba7968f6
Revises: a4f80f2a191c
Create Date: 2025-11-21 17:43:50.002091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0cba7968f6'
down_revision: Union[str, Sequence[str], None] = 'a4f80f2a191c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('channels', 'username',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'username',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('channels', 'title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
