"""add media for raffle

Revision ID: cd52c78f20fa
Revises: 3e37106dfd45
Create Date: 2025-11-19 11:16:53.335006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd52c78f20fa'
down_revision: Union[str, Sequence[str], None] = '3e37106dfd45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffles', sa.Column('photo_id', sa.String(length=100), nullable=True))
    op.add_column('raffles', sa.Column('video_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'video_id')
    op.drop_column('raffles', 'photo_id')
    # ### end Alembic commands ###
