"""add delete channels

Revision ID: fe7d33d949d3
Revises: af5e9838238c
Create Date: 2025-12-04 17:38:46.138298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7d33d949d3'
down_revision: Union[str, Sequence[str], None] = 'af5e9838238c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('raffle_channels_channel_id_fkey'), 'raffle_channels', type_='foreignkey')
    op.create_foreign_key(None, 'raffle_channels', 'channels', ['channel_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raffle_channels', type_='foreignkey')
    op.create_foreign_key(op.f('raffle_channels_channel_id_fkey'), 'raffle_channels', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###
